version: "3.4"

services:
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=WineCatalog;Integrated Security=False;User ID=sa;Password=StrongPwd#123;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
    ports:
      - "3000:80"

  db:
    ports:
      - "1433:1433"
