version: '3.4'

services:
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog/Dockerfile

  db:
    image: ${DOCKER_REGISTRY-}db
    build:
      context: .
      dockerfile: mssqldb/Dockerfile 